### ISSUE TITLE
Unable To Open GPX Recording screen

### ISSUE THREAD

**Issue by Brennan-Walsh** [peterLaurence/TrekAdvisor#28]
Hi 

I have compiled the trekadvisor and the only think that i can get to work is the GPX Record. Then i try to click on the GPS REcord the APP closes. What am I doing wrong

**Comment by Brennan-Walsh** [comment]
it seems that the first time you try and run the recording screen  you need to have one GPX file in the recording folder. You cannot update the recording list if their are no records in the folder. 

    public RecordListView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

        updateRecordings(); 
        init(context, attrs);
    }

    private void updateRecordings() {
        mRecordings.clear();
        mRecordings.addAll(Arrays.asList(TrackImporter.getRecordings()));
    }

**Comment by peterLaurence** [comment]
Hi,

Thanks for reporting this. I will have look at that soon.

Le lun. 12 mars 2018 à 16:17, Brennan-Walsh <notifications@github.com> a
écrit :

**Comment by peterLaurence** [comment]
@Brennan-Walsh  This should be fixed now.
