### ISSUE TITLE
New logo for TrekAdvisor

### ISSUE THREAD

**Issue by zularizal** [peterLaurence/TrekAdvisor#31]
Hello, I want contribute to TrekAdvisor , I designed a logo fot TrekAdvisor. You can choose which one you like, without square or square. I hope you like it. If you like it, i will send pr dan original files. If there's something you want to change. I'll do it.

![logo](https://user-images.githubusercontent.com/38547278/39105472-458a27fc-46e0-11e8-9f84-870bcfee7574.png)

**Comment by peterLaurence** [comment]
Hi, nice work here. I like it with the square.
Out of curiosity, do you use trekadvisor? How?
Thanks for your contribution.

**Comment by peterLaurence** [comment]
Hi haven't uploaded to the play store yet. I need to finish the in-app map creation functionality.
I expect to have this done in about one month.
