### ISSUE TITLE
Map not refreshing after gpx record import

### ISSUE THREAD

**Issue by Brennan-Walsh** [peterLaurence/TrekAdvisor#45]
Hi 

I would like to report a bug. 

If i select a map (eg. world map) and then go to gpx recording and import a recorded gpx file which was recorded using the trekadvisor app and then go back to the world map, the maps does not show the gpx recorded file. The only way i can get the recorded gpx file to show up is to select a different map and then go back to the world map. So the map is not refreshing after gpx file is imported from the gpx recorder. The other option is to close and reopen the app to get the map to refresh with the newly  recorded gpx file.

**Comment by peterLaurence** [comment]
Thanks for submitting this issue. Indeed, i can reproduce this. Actually, instead of opening another map,  zooming in makes the track appear (for me at least).

[technical reminder : there's probably a missing invalidate() when adding a track to a map]

**Comment by peterLaurence** [comment]
The fix will be part of next version.
